language: go

os:
    - linux
    - osx

sudo: false

go:
    - 1.7
    - tip

before_install:
    - mkdir -p $GOPATH/bin
    - curl https://glide.sh/get | sh
install: make install
script: make VERBOSE=true test
