language: go

os:
    - linux
    - osx

sudo: false

go:
    - 1.7
    - tip

before_install:
    - mkdir -p $HOME/bin
    - curl -L https://git.io/vMZjG | sh -s $HOME/bin
install: make install
script: make VERBOSE=true test
