// Code generated by go-bindata.
// sources:
// data/assets/css/style.css
// data/templates/index.html
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataAssetsCssStyleCss = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x74\x90\xd1\x6e\xea\x30\x0c\x86\xef\x79\x0a\x4b\xe7\x96\xa0\xb4\x07\x36\x14\xa4\xbd\x4b\x68\x9d\x36\x5b\x12\x47\x89\x19\x74\xd3\xde\x7d\x02\x32\x46\xbb\x72\x53\x55\x9f\xf3\xdb\x9f\xfe\x95\xd7\x21\xea\x0e\xe1\x73\x01\x60\x28\xb0\x30\xda\x5b\x37\x28\xf0\x14\x28\x47\xdd\xe0\xee\x67\x92\xed\x07\x2a\xa8\xd6\xf1\x74\x46\xce\x06\x14\x3d\xda\xae\x67\x05\xd5\x6a\x5d\x6f\x37\xcf\x55\xf9\xfe\x3f\x3f\xf0\xfa\x24\x8e\xb6\xe5\x5e\xc1\x56\xca\x6b\x88\xf1\xc4\x42\x3b\xdb\x05\x05\xaf\x87\xcc\xd6\x0c\x3b\xf8\x5a\x00\xdc\x3c\xfa\xea\xa2\x32\x3a\x59\x97\xf4\xe4\x68\x3d\x8d\xd6\x7f\xa3\xd5\xd3\x6c\xb4\x5a\xd5\x9b\x2b\xf6\x3a\x75\x36\x08\xa6\x78\x7f\xa7\xd0\x3d\x31\x93\x57\x20\xaf\xf4\x62\xcf\x49\x87\x6c\x28\x79\x05\x87\x18\x31\x35\x3a\xe3\x44\x44\x2f\xef\xfe\x95\xb3\xe1\x6d\x04\x7a\x7a\xc7\x54\x54\x1b\x72\x94\x14\xfc\x93\x52\x4a\x63\x76\xbf\xfa\xc7\x62\xba\x27\xd7\x4e\xd6\x67\x6c\xd8\x52\x80\x17\x88\xcb\x39\x7a\x70\xb3\x98\xe6\x71\x43\x2d\xce\x0e\x62\xc2\x22\x79\xdf\x91\x1c\x15\xe4\xd0\xb0\x82\xcd\xb9\xb7\x47\x8e\x0f\x6d\xca\xf2\xa8\xdb\xd6\x86\xee\xb6\xd9\xd9\xcc\x22\xf3\xe0\x50\xf0\x10\x51\x41\xa0\x70\x29\xf8\x3b\x00\x00\xff\xff\x84\x61\x9b\xd8\xab\x02\x00\x00")

func dataAssetsCssStyleCssBytes() ([]byte, error) {
	return bindataRead(
		_dataAssetsCssStyleCss,
		"data/assets/css/style.css",
	)
}

func dataAssetsCssStyleCss() (*asset, error) {
	bytes, err := dataAssetsCssStyleCssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/assets/css/style.css", size: 683, mode: os.FileMode(420), modTime: time.Unix(1483334580, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dataTemplatesIndexHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb4\x54\xc1\x8e\xd3\x30\x10\xbd\xf7\x2b\x46\x3e\xc1\x61\x63\xb5\x27\x0e\x8e\x4f\xbb\xec\x09\xb4\x12\x45\x1c\x10\x42\x26\x99\xd6\x16\x8e\x13\xec\xa9\x44\x65\xe5\xdf\x91\xe3\x94\x06\x9a\x94\x05\xd4\x63\xe7\xcd\x9b\xf7\x3a\x2f\x1e\xa1\xa9\xb1\x72\x25\x34\xaa\x5a\xae\x00\x00\x44\x83\xa4\xa0\xd2\xca\x07\xa4\x92\xbd\xdf\xbe\xbe\x7b\xc5\x46\x88\x0c\x59\x94\x31\x16\x6f\x55\x83\x7d\xff\x62\xfd\x52\xf0\x5c\xcb\xb8\x35\xee\x2b\x78\xb4\x25\x0b\x74\xb4\x18\x34\x22\x31\xa0\x63\x87\x25\x23\xfc\x4e\xbc\x0a\x81\x81\xf6\xb8\x2b\x19\xff\xac\x42\x40\x0a\xa9\xc6\x87\xf6\x22\xa1\x72\x25\x78\x36\x23\xbe\xb4\xf5\xf1\xe4\x49\x19\x07\x95\x55\x21\x94\xac\x51\xae\x53\x7b\x1c\x3d\x0d\xb0\x5e\xff\x66\x4a\xaf\xe5\xea\x0c\x07\xac\xc8\xb4\x0e\x4c\x5d\x32\xa7\x9a\x29\x35\xd3\x37\x32\x71\x05\xd7\x9b\x09\x6d\x80\xba\xf3\x60\xb8\x83\x18\x8b\x77\xba\xf5\x74\x8f\xa1\xf2\xa6\x4b\x43\xfb\x5e\xf0\x6e\x62\x85\x8f\x62\x4b\xfa\xf5\x99\x3a\x63\x63\x32\x78\xd1\xcd\x7f\x88\xa3\xab\xbb\xd6\x38\x0a\x33\xd2\x0f\x27\x6c\x4e\xf8\x60\x7f\x25\x8c\x69\x4b\xa1\x4e\x69\x32\xc9\x05\x57\x12\xb6\xda\x04\x48\xf9\x08\x6e\xcd\x25\x29\x46\xaf\xdc\x1e\xa1\xf8\x29\xd7\xf7\x17\x4d\xb9\xd1\xec\x00\xbf\x41\xf1\x06\x49\xb7\x35\xb0\xc7\x87\x2d\x5b\xe8\xbd\x70\x13\x63\xf1\xe4\xb1\x53\x1e\x3f\x18\xd2\xf7\xb8\x53\x07\x9b\x94\x58\xda\xdf\x93\x22\x9d\x16\xa7\x24\x5c\x6e\x73\xce\x73\xb6\x83\x36\xe0\x9f\xf4\x03\xf9\xd6\xed\xa7\x22\x63\x05\x3e\xc6\x38\xfe\x93\xbe\xff\xf4\x77\xba\xae\x9e\x91\x3d\xd5\x97\x17\xfc\xe8\xdb\x43\xb7\xb4\xdd\xc1\xad\xde\x9c\x3f\xee\x21\xf4\x6b\x36\x9e\x19\x1b\xfc\x43\x74\x70\xfb\xf8\xe0\x39\x11\xc2\xed\x62\x84\x2b\x51\x5e\xc3\xe6\xea\x82\x4f\x5f\xe3\xe4\xcd\xe7\x9f\xe9\x54\xa6\x23\x9a\xaf\xa7\xe0\xf9\xc0\xff\x08\x00\x00\xff\xff\xb7\x39\x27\xe3\xe8\x05\x00\x00")

func dataTemplatesIndexHtmlBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplatesIndexHtml,
		"data/templates/index.html",
	)
}

func dataTemplatesIndexHtml() (*asset, error) {
	bytes, err := dataTemplatesIndexHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/templates/index.html", size: 1512, mode: os.FileMode(420), modTime: time.Unix(1483336025, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/assets/css/style.css": dataAssetsCssStyleCss,
	"data/templates/index.html": dataTemplatesIndexHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"assets": &bintree{nil, map[string]*bintree{
			"css": &bintree{nil, map[string]*bintree{
				"style.css": &bintree{dataAssetsCssStyleCss, map[string]*bintree{}},
			}},
		}},
		"templates": &bintree{nil, map[string]*bintree{
			"index.html": &bintree{dataTemplatesIndexHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

