// Code generated by go-bindata.
// sources:
// data/assets/css/style.css
// data/templates/index.html
// DO NOT EDIT!

package bingo

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataAssetsCssStyleCss = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x74\x90\xd1\x6e\xea\x30\x0c\x86\xef\x79\x0a\x4b\xe7\x96\xa0\xb4\x07\x36\x14\xa4\xbd\x4b\x68\x9d\x36\x5b\x12\x47\x89\x19\x74\xd3\xde\x7d\x02\x32\x46\xbb\x72\x53\x55\x9f\xf3\xdb\x9f\xfe\x95\xd7\x21\xea\x0e\xe1\x73\x01\x60\x28\xb0\x30\xda\x5b\x37\x28\xf0\x14\x28\x47\xdd\xe0\xee\x67\x92\xed\x07\x2a\xa8\xd6\xf1\x74\x46\xce\x06\x14\x3d\xda\xae\x67\x05\xd5\x6a\x5d\x6f\x37\xcf\x55\xf9\xfe\x3f\x3f\xf0\xfa\x24\x8e\xb6\xe5\x5e\xc1\x56\xca\x6b\x88\xf1\xc4\x42\x3b\xdb\x05\x05\xaf\x87\xcc\xd6\x0c\x3b\xf8\x5a\x00\xdc\x3c\xfa\xea\xa2\x32\x3a\x59\x97\xf4\xe4\x68\x3d\x8d\xd6\x7f\xa3\xd5\xd3\x6c\xb4\x5a\xd5\x9b\x2b\xf6\x3a\x75\x36\x08\xa6\x78\x7f\xa7\xd0\x3d\x31\x93\x57\x20\xaf\xf4\x62\xcf\x49\x87\x6c\x28\x79\x05\x87\x18\x31\x35\x3a\xe3\x44\x44\x2f\xef\xfe\x95\xb3\xe1\x6d\x04\x7a\x7a\xc7\x54\x54\x1b\x72\x94\x14\xfc\x93\x52\x4a\x63\x76\xbf\xfa\xc7\x62\xba\x27\xd7\x4e\xd6\x67\x6c\xd8\x52\x80\x17\x88\xcb\x39\x7a\x70\xb3\x98\xe6\x71\x43\x2d\xce\x0e\x62\xc2\x22\x79\xdf\x91\x1c\x15\xe4\xd0\xb0\x82\xcd\xb9\xb7\x47\x8e\x0f\x6d\xca\xf2\xa8\xdb\xd6\x86\xee\xb6\xd9\xd9\xcc\x22\xf3\xe0\x50\xf0\x10\x51\x41\xa0\x70\x29\xf8\x3b\x00\x00\xff\xff\x84\x61\x9b\xd8\xab\x02\x00\x00")

func dataAssetsCssStyleCssBytes() ([]byte, error) {
	return bindataRead(
		_dataAssetsCssStyleCss,
		"data/assets/css/style.css",
	)
}

func dataAssetsCssStyleCss() (*asset, error) {
	bytes, err := dataAssetsCssStyleCssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/assets/css/style.css", size: 683, mode: os.FileMode(420), modTime: time.Unix(1483334580, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dataTemplatesIndexHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb4\x54\x4d\x8f\xd3\x30\x10\xbd\xf7\x57\x8c\x7c\x82\xc3\xc6\x6a\x4f\x1c\x1c\x9f\x58\xf6\x04\x42\xa2\x7b\x42\x08\x99\x64\xb6\xb6\x70\x9c\x60\xcf\x4a\x54\x96\xff\x3b\x72\x9c\xd2\x40\x93\xb2\x7c\x1d\x33\x6f\xde\xbc\xa7\x79\xf1\x08\x4d\x9d\x95\x1b\xa1\x51\xb5\x72\x03\x00\x20\x3a\x24\x05\x8d\x56\x3e\x20\xd5\xec\x7e\xff\xea\xe6\x05\x9b\x20\x32\x64\x51\xc6\x58\xbd\x51\x1d\xa6\xf4\x6c\xfb\x5c\xf0\x52\x2b\xb8\x35\xee\x33\x78\xb4\x35\x0b\x74\xb4\x18\x34\x22\x31\xa0\xe3\x80\x35\x23\xfc\x4a\xbc\x09\x81\x81\xf6\xf8\x50\x33\xfe\x51\x85\x80\x14\x72\x8d\x8f\xed\x55\x46\xe5\x46\xf0\x62\x46\x7c\xea\xdb\xe3\xc9\x93\x32\x0e\x1a\xab\x42\xa8\x59\xa7\xdc\xa0\x0e\x38\x79\x1a\x61\xbd\xfd\xc9\x94\xde\xca\xcd\x19\x0e\xd8\x90\xe9\x1d\x98\xb6\x66\x4e\x75\x73\x6a\xa1\xef\x64\xe6\x0a\xae\x77\x33\xda\x08\x0d\xe7\xc1\x70\x03\x31\x56\xef\x74\xef\xe9\x25\x86\xc6\x9b\x21\x0f\x4d\x49\xf0\x61\x66\x85\x4f\x62\x6b\xfa\xed\x99\xba\x60\x63\x36\x78\xd5\xcd\x5f\x88\xa3\x6b\x87\xde\x38\x0a\x0b\xd2\xb7\x27\x6c\x49\xf8\xd1\xfe\x48\x98\xd2\x96\x42\x9d\xd2\x64\x92\x0b\xae\x24\xec\xb5\x09\x90\xf3\x11\xdc\x9a\x4b\x52\x8c\x5e\xb9\x03\x42\xf5\x5d\x2e\xa5\x8b\xa6\xd2\x68\x1e\x00\xbf\x40\xf5\x1a\x49\xf7\x2d\xb0\xbb\xdb\x3d\x5b\xe9\xbd\x70\x13\x63\x75\xef\x6d\x4a\x2c\xef\xeb\xad\x22\x9d\x17\xa5\x24\x5c\x6e\x6f\xc9\x63\x91\x47\x1b\xf0\x57\x7a\x81\x7c\xef\x0e\x73\x91\xa9\x02\xef\x63\x9c\x9c\xa7\xf4\xe1\xf7\x74\x5d\xbb\x20\x7b\xaa\xaf\x2f\xf4\xce\xf7\x8f\xc3\xda\x36\x47\xb7\x7a\x77\xfe\x99\xc7\x90\xaf\xd9\x78\x62\x4c\xf0\x07\x51\xc1\xbf\x8f\x0b\x9e\x12\x19\xfc\xbf\xd8\xe0\x4a\x74\xd7\xb0\xa5\xba\xe0\xf3\xd7\x36\x7b\xd3\xe5\x33\x9f\xc2\x7c\x24\xcb\x75\x14\xbc\x1c\xf0\x6f\x01\x00\x00\xff\xff\x8b\xdd\x34\x27\xc8\x05\x00\x00")

func dataTemplatesIndexHtmlBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplatesIndexHtml,
		"data/templates/index.html",
	)
}

func dataTemplatesIndexHtml() (*asset, error) {
	bytes, err := dataTemplatesIndexHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/templates/index.html", size: 1480, mode: os.FileMode(420), modTime: time.Unix(1483458804, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/assets/css/style.css": dataAssetsCssStyleCss,
	"data/templates/index.html": dataTemplatesIndexHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"assets": &bintree{nil, map[string]*bintree{
			"css": &bintree{nil, map[string]*bintree{
				"style.css": &bintree{dataAssetsCssStyleCss, map[string]*bintree{}},
			}},
		}},
		"templates": &bintree{nil, map[string]*bintree{
			"index.html": &bintree{dataTemplatesIndexHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

